export const postsData = [
  {
    id: 1,
    image: "https://placehold.co/600x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "1 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: false,
    popular: true,
    author: 4,
  },
  {
    id: 2,
    image: "https://placehold.co/400x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "2 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: true,
    popular: false,
    author: 5,
  },
  {
    id: 3,
    image: "https://placehold.co/400x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "3 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: false,
    popular: true,
    author: 3,
  },
  {
    id: 4,
    image: "https://placehold.co/400x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "4 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: true,
    popular: false,
    author: 4,
  },
  {
    id: 5,
    image: "https://placehold.co/400x400",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "5 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: true,
    popular: false,
    author: 5,
  },
  {
    id: 6,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "6 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: true,
    popular: true,
    author: 3,
  },
  {
    id: 7,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "7 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: true,
    popular: true,
    author: 4,
  },
  {
    id: 8,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "8 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: true,
    popular: true,
    author: 5,
  },
  {
    id: 9,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "9 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: false,
    popular: false,
    author: 3,
  },
  {
    id: 10,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "10 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: false,
    popular: false,
    author: 5,
  },
  {
    id: 11,
    image: "https://placehold.co/100x100",
    text: "Lorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem IpsumLorem Ipsum is Lorem Ipsum and Lorem Ipsum is aute mud Lore maiore magna. Lorem Ipsum is Lorem Ipsum, Lorem Ips lorem temp tempus. Lorem Ipsum",
    date: "2021-12-12",
    lesson_num: 1,
    title: "11 Lorem Ipsum is Lorem Ipsum Lorem Ipsum is Lorem Ipsum",
    favourites: false,
    popular: false,
    author: 3,
  },
];
